---
  - name: Install epel-release repo
    yum:
      name: "epel-release"
      state: latest

  - name: Install Require packages
    yum:
      name: "{{ item }}"
      state: latest
    loop: "{{ package_list }}"  

  - name: Start and enable require services
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop: "{{ service_list }}"  


  - name: Mysql Secure installation
    community.mysql.mysql_user:
      name: root
      password: "{{ roots_passwd }}"
      login_password: "{{ roots_passwd }}"
        
  - name: Copy phpmyadmin Template
    template:
      dest: "/etc/httpd/conf.d/phpMyAdmin.conf"
      src: phpMyAdmin.conf.j2
    
  - name: Add services to the firewall
    firewalld:
      state: enabled
      service: "{{ item }}"
      permanent: yes
      immediate: yes
    loop: "{{ firewall_services }}"  
    
  - name: Restart httpd
    service:
      name: httpd 
      state: restarted

  - name: Copy identity file
    template:
      dest: /root/.my.cnf
      src: my.cnf.j2
      
  - name: Copy database query file
    copy:
      src: database.sql
      dest: /root/database.sql

  - name: Adding entries into a database
    shell: 
      chdir: /root
      cmd: mysql < database.sql 

#  - name: Dump SpringDevOps2021 database
#    mysql_db:
#      name: SprinDevOps2021
#      state: dump
#      target: /tmp/SpringDevOps2021_backup.sql
      
      
#  - name: Remove database SpringDevOps2021
#    mysql_db:
#      name: SpringDevOps2021
#      state: absent 
#  - name: create SpringDevOps2021
#    mysql_db:
#      name: SprinDevOps2021
#      state: present
#
#  - name: Recover from backup
#    mysql_db:
#      name: SprinDevOps2021
#      state: import
#      target: /tmp/SpringDevOps2021_backup.sql    


# the last 4 tasks are examples on how to dump and create and recover databases



