---
  - name: Installing Apache webserver
    hosts: 192.168.1.52
    vars:
      html_message: "This is the  nginx/html server  with when: condition arguments for both"
    become: yes
    tasks:
      - name: Set Document Root for apache
        set_fact:
          doc_root: "/var/www/html"
        when: pckg_name == "httpd" 

      - name: Set Document Root for nginx
        set_fact:
          doc_root: "/usr/share/nginx/html"
        when: pckg_name == "nginx"

      - name: Install epel-release repo
        yum: 
          name: epel-release
          state: present
        when: pckg_name  == "nginx"

      - name: Installing a package
        yum: 
          name: "{{ pckg_name }}"
          state: present

      - name: Start amd enable a service
        service:
          name: "{{ pckg_name }}"
          state: started
          enabled: yes

      - name: Add firewall rule
        firewalld:
          state: enabled
          service: http
          permanent: yes
          immediate: yes

      - name: Add index.html file
        copy:
          dest: "{{ doc_root }}/index.html"
          content: "{{ html_message }}"  




# ansible-playbook -i new_invent playbooks/webserver-nginx.yml --extra-vars "pckg_name=httpd" 
# ansible-playbook -i new_invent playbooks/webserver-nginx.yml --extra-vars "pckg_name=nginx"           