---
  - name: Installing Apache webserver
    hosts: 192.168.1.51
    vars:
      pckg_name: httpd
      html_message: "This is the 1st webserver with ansible using a playbook with VARS"
    become: yes
    tasks: 
      - name: Installing a package
        yum: 
          name: "{{ pckg_name }}"
          state: latest

      - name: Start amd enable a service
        service:
          name: "{{ pckg_name }}"
          state: started
          enabled: yes

      - name: Add firewall rule
        firewalld:
          state: enabled
          service: http
          permanent: yes
          immediate: yes

      - name: Add index.html file
        copy:
          dest: /var/www/html/index.html
          content: "{{ html_message }}"  
