---
# vars file for roles/paulo.nagios-client
nagios_server_ip: 192.168.1.54

check_commands:
   - command[check_users]=/usr/lib64/nagios/plugins/check_users -w 5 -c 10 
   - command[check_load]=/usr/lib64/nagios/plugins/check_load -r -w .15,.10,.05 -c .30,.25,.20
   - command[check_hda1]=/usr/lib64/nagios/plugins/check_disk -w 20% -c 10% -p /dev/hda1
   - command[check_zombie_procs]=/usr/lib64/nagios/plugins/check_procs -w 5 -c 10 -s Z 
   - command[check_total_procs]=/usr/lib64/nagios/plugins/check_procs -w 150 -c 200
   - command[check_ntp]=/usr/lib64/nagios/plugins/check_ntp_time -H 192.168.1.161 -w 0.5 -c 1
   - command[check_disk]=/usr/lib64/nagios/plugins/check_disk -w 20% -c 10% -p /
   - command[check_swap]=/usr/lib64/nagios/plugins/check_swap -w 20% -c 10%
   - command[check_dns]=/usr/lib64/nagios/plugins/check_dns -H 192.168.1.162  -s 192.168.1.170 -q ANY














 # - "command[check_disk]=/usr/lib64/nagios/plugins/check_disk -w 20% -c 10% -p /"
  #- "command[check_disk]=/usr/lib64/nagios/plugins/check_swap -w 20% -c 10%"
  #- "command[check_disk]=/usr/lib64/nagios/plugins/check_dns -H devx-web001.local -s 192.168.1.201 -q ANY" # this is the DNS ip